import './globals.css'
import {ClusterProvider} from '@/components/cluster/cluster-data-access'
import {SolanaProvider, WalletButton} from '@/components/solana/solana-provider'
import {UiLayout} from '@/components/ui/ui-layout'
import {ReactQueryProvider} from './react-query-provider'
import { Toaster } from 'react-hot-toast'

export const metadata = {
  title: 'Tita',
  description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Clusters', path: '/clusters' },
  { label: 'Basic Program', path: '/basic' },
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <div>
                <Toaster />
                <div className='container mx-auto min-h-screen'>
                  <div className='navbar flex justify-between items-center'>
                    <div className='text-3xl font-semibold text-primary'>
                      Tita
                    </div>
                    <div>
                      <WalletButton />
                    </div>
                  </div>
                  {children}
                </div>
                <div className='flex justify-center'>
                  &#169; Antoni. All rights reserved
                </div>
              </div>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
